Scriptname a0aLOADS_QST_ManualScript extends Quest
{Handles the manual override triggers from MCM}

Keyword Property a0aLOADS_KYWD_Manual_ScopeZoomMax Auto

Keyword Property a0aLOADS_OMOD_Manual_ScopeZoomMax_2x Auto
Keyword Property a0aLOADS_OMOD_Manual_ScopeZoomMax_4x Auto
Keyword Property a0aLOADS_OMOD_Manual_ScopeZoomMax_6x Auto
Keyword Property a0aLOADS_OMOD_Manual_ScopeZoomMax_10x Auto
Keyword Property a0aLOADS_OMOD_Manual_ScopeZoomMax_Default Auto

Keyword Property a0aLOADS_KYWD_ScopeZoomMax_2x Auto
Keyword Property a0aLOADS_KYWD_ScopeZoomMax_4x Auto
Keyword Property a0aLOADS_KYWD_ScopeZoomMax_6x Auto
Keyword Property a0aLOADS_KYWD_ScopeZoomMax_10x Auto